require 'anagram_solver/routing'
require 'anagram_solver/finder'
require 'anagram_solver/permutator'
require 'anagram_solver/file_manager'
require 'anagram_solver/async_consumer'
require 'anagram_solver/middleware'
require 'anagram_solver/engine'
